package javacamod.content;

import arc.graphics.*;
import arc.graphics.g2d.*;
import arc.struct.*;
import arc.util.*;
import arc.graphics.*;
import arc.math.*;
import arc.struct.*;
import mindustry.*;
import mindustry.content.*;
import mindustry.entities.*;
import mindustry.entities.abilities.*;
import mindustry.entities.bullet.*;
import mindustry.entities.effect.*;
import mindustry.entities.part.DrawPart.*;
import mindustry.entities.part.*;
import mindustry.entities.pattern.*;
import mindustry.gen.*;
import mindustry.graphics.*;
import mindustry.type.*;
import mindustry.type.unit.*;
import mindustry.world.*;
import mindustry.world.blocks.*;
import mindustry.world.blocks.campaign.*;
import mindustry.world.blocks.defense.*;
import mindustry.world.blocks.defense.turrets.*;
import mindustry.world.blocks.distribution.*;
import mindustry.world.blocks.environment.*;
import mindustry.world.blocks.heat.*;
import mindustry.world.blocks.legacy.*;
import mindustry.world.blocks.liquid.*;
import mindustry.world.blocks.logic.*;
import mindustry.world.blocks.payloads.*;
import mindustry.world.blocks.power.*;
import mindustry.world.blocks.production.*;
import mindustry.world.blocks.sandbox.*;
import mindustry.world.blocks.storage.*;
import mindustry.world.blocks.units.*;
import mindustry.world.consumers.*;
import mindustry.world.draw.*;
import mindustry.world.meta.*;

import static mindustry.Vars.*;

public class JavacamodUnitTypesOverride{
  public static void init(){

    UnitTypes.dagger.buildSpeed = 1;
    UnitTypes.mace.buildSpeed = 1;
    UnitTypes.fortress.buildSpeed = 1;
    UnitTypes.scepter.buildSpeed = 1;
    UnitTypes.reign.buildSpeed = 1;
    UnitTypes.crawler.buildSpeed = 1;
    UnitTypes.atrax.buildSpeed = 1;
    UnitTypes.spiroct.buildSpeed = 1;
    UnitTypes.arkyid.buildSpeed = 1;
    UnitTypes.toxopid.buildSpeed = 1;
    UnitTypes.nova.buildSpeed = 1;
    UnitTypes.pulsar.buildSpeed = 1;
    UnitTypes.quasar.buildSpeed = 1;
    UnitTypes.vela.buildSpeed = 1;
    UnitTypes.corvus.buildSpeed = 1;
    UnitTypes.flare.buildSpeed = 1;
    UnitTypes.horizon.buildSpeed = 1;
    UnitTypes.zenith.buildSpeed = 1;
    UnitTypes.antumbra.buildSpeed = 1;
    UnitTypes.eclipse.buildSpeed = 1;
    UnitTypes.mono.buildSpeed = 1;
    UnitTypes.poly.buildSpeed = 1;
    UnitTypes.mega.buildSpeed = 1;
    UnitTypes.quad.buildSpeed = 1;
    UnitTypes.oct.buildSpeed = 1;
    UnitTypes.risso.buildSpeed = 1;
    UnitTypes.minke.buildSpeed = 1;
    UnitTypes.bryde.buildSpeed = 1;
    UnitTypes.sei.buildSpeed = 1;
    UnitTypes.omura.buildSpeed = 1;
    UnitTypes.retusa.buildSpeed = 1;
    UnitTypes.oxynoe.buildSpeed = 1;
    UnitTypes.cyerce.buildSpeed = 1;
    UnitTypes.aegires.buildSpeed = 1;
    UnitTypes.navanax.buildSpeed = 1;
    UnitTypes.stell.buildSpeed = 1;
    UnitTypes.locus.buildSpeed = 1;
    UnitTypes.precept.buildSpeed = 1;
    UnitTypes.vanquish.buildSpeed = 1;
    UnitTypes.conquer.buildSpeed = 1;
    UnitTypes.merui.buildSpeed = 1;
    UnitTypes.cleroi.buildSpeed = 1;
    UnitTypes.anthicus.buildSpeed = 1;
    UnitTypes.tecta.buildSpeed = 1;
    UnitTypes.collaris.buildSpeed = 1;
    UnitTypes.elude.buildSpeed = 1;
    UnitTypes.avert.buildSpeed = 1;
    UnitTypes.obviate.buildSpeed = 1;
    UnitTypes.quell.buildSpeed = 1;
    UnitTypes.disrupt.buildSpeed = 1;
    UnitTypes.renale.buildSpeed = 1;
    UnitTypes.renale.hidden = false;
    UnitTypes.latum.buildSpeed = 1;
    UnitTypes.latum.hidden = false;

  }
}
